// awesome-neobank provider data
// Sources: neobank.build/providers (seed) + independent research, July 2026.
// Schema: name, url, docs (optional), description, categories[], tags[], featured (optional)

const CATEGORIES = [
  { id: "full-stack", label: "Full-stack solutions", blurb: "Vertically integrated platforms: accounts, ramps, compliance, cards, and settlement behind one API." },
  { id: "baas", label: "Banking-as-a-Service", blurb: "Licensed banking programs, sponsor banks, and embedded finance platforms." },
  { id: "ledger", label: "Core banking & ledgers", blurb: "Systems of record: core banking platforms and programmable ledgers." },
  { id: "cards", label: "Cards & issuing", blurb: "Card issuing, processing, and program management." },
  { id: "kyc", label: "KYC & onboarding", blurb: "Identity verification, KYB, and customer onboarding." },
  { id: "compliance", label: "Compliance & fraud", blurb: "AML, transaction monitoring, fraud prevention, and blockchain analytics." },
  { id: "payments", label: "Payment operations", blurb: "Money movement over bank rails: ACH, RTP, wires, and payouts." },
  { id: "virtual-accounts", label: "Virtual accounts", blurb: "Named virtual ACH and IBAN accounts for deposits and bank-to-wallet flows." },
  { id: "ramps", label: "Onramps & offramps", blurb: "Fiat-to-crypto and crypto-to-fiat conversion, global and regional." },
  { id: "fx", label: "Cross-border & FX", blurb: "International payments, local rails, and currency conversion." },
  { id: "openbanking", label: "Open banking & data", blurb: "Bank account connectivity, data aggregation, and pay by bank." },
  { id: "custody", label: "Custody & wallets", blurb: "Embedded wallets, key management, and institutional custody." },
  { id: "stablecoins", label: "Stablecoins", blurb: "Issuers and issuance platforms for fiat-backed digital currencies." },
  { id: "networks", label: "Settlement networks", blurb: "Blockchains used as settlement rails." },
  { id: "swaps", label: "Swaps & bridging", blurb: "Cross-chain routing, bridging, and token swaps." },
  { id: "yield", label: "Yield & earn", blurb: "Lending protocols and yield infrastructure for earn products." },
];

const PROVIDERS = [
  // ---- Full-stack solutions ----
  { name: "Open Money Stack", url: "https://polygon.technology", docs: "https://docs.polygon.technology/oms/overview", description: "Polygon's vertically integrated stack for global money movement: ramps, wallets, compliance, routing, and settlement in one API.", categories: ["full-stack"], tags: ["stablecoin", "global"], featured: true },
  { name: "Bridge", url: "https://bridge.xyz", docs: "https://apidocs.bridge.xyz", description: "Stablecoin orchestration and issuance, virtual accounts, and cards, from Stripe.", categories: ["full-stack", "virtual-accounts", "ramps", "stablecoins", "cards"], tags: ["stablecoin", "US", "global"] },
  { name: "BVNK", url: "https://bvnk.com", docs: "https://docs.bvnk.com", description: "Stablecoin payment infrastructure with virtual accounts, wallets, and ramps.", categories: ["full-stack", "virtual-accounts", "ramps", "stablecoins"], tags: ["stablecoin", "EU", "UK", "global"] },
  { name: "Zero Hash", url: "https://zerohash.com", docs: "https://docs.zerohash.com", description: "Regulated crypto and stablecoin infrastructure: custody, trading, ramps, and payouts.", categories: ["full-stack", "custody", "ramps"], tags: ["crypto", "stablecoin", "US", "global"] },
  { name: "Rain", url: "https://rain.xyz", description: "Visa principal member issuing stablecoin-funded cards in 150+ countries; acquired Fern.", categories: ["full-stack", "cards"], tags: ["stablecoin", "US", "global"] },
  { name: "Fern", url: "https://fernhq.com", docs: "https://docs.fernhq.com", description: "Onramps, offramps, FX, and multi-currency accounts in one API; part of Rain.", categories: ["full-stack", "ramps", "fx"], tags: ["stablecoin", "global"] },
  { name: "Crossmint", url: "https://crossmint.com", docs: "https://docs.crossmint.com", description: "Wallets, stablecoin ramps, cards, and built-in compliance in one API.", categories: ["full-stack", "custody", "ramps"], tags: ["stablecoin", "global"] },
  { name: "Stripe", url: "https://stripe.com", description: "Payments platform with stablecoin accounts, card issuing, Bridge, and Privy.", categories: ["full-stack", "payments", "ramps", "cards"], tags: ["fiat", "stablecoin", "global"] },
  { name: "Altitude", url: "https://altitude.xyz", description: "Self-custodial digital asset accounts with compliance, ramps, cards, and rewards.", categories: ["full-stack", "virtual-accounts", "ramps", "cards", "yield"], tags: ["stablecoin", "global"] },
  { name: "Dakota", url: "https://dakota.xyz", docs: "https://docs.dakota.xyz", description: "Business banking on stablecoin and treasury rails: accounts, payments, and cards.", categories: ["full-stack", "virtual-accounts"], tags: ["stablecoin", "US"] },
  { name: "Squads Grid", url: "https://squads.xyz", docs: "https://grid.squads.xyz", description: "Stablecoin accounts, payments, cards, and yield APIs built on Solana.", categories: ["full-stack", "custody"], tags: ["stablecoin", "US", "global"] },
  { name: "Mural Pay", url: "https://muralpay.com", docs: "https://developers.muralpay.com", description: "Named USD and EUR virtual accounts, stablecoin payouts, and compliance APIs.", categories: ["full-stack", "virtual-accounts", "ramps"], tags: ["stablecoin", "US", "EU", "LATAM"] },
  { name: "Triple-A", url: "https://triple-a.io", docs: "https://developers.triple-a.io", description: "Licensed stablecoin payments, payouts, and multicurrency accounts across 70+ countries.", categories: ["full-stack", "ramps"], tags: ["stablecoin", "APAC", "global"] },
  { name: "FV Bank", url: "https://fvbank.us", description: "Licensed US bank with API banking, digital asset custody, and stablecoin payments.", categories: ["full-stack", "baas", "custody"], tags: ["fiat", "stablecoin", "US"] },

  // ---- Banking-as-a-Service ----
  { name: "Unit", url: "https://unit.co", docs: "https://unit.co/docs", description: "Embedded finance platform for accounts, cards, payments, and lending via partner banks.", categories: ["baas"], tags: ["fiat", "US"] },
  { name: "Treasury Prime", url: "https://treasuryprime.com", description: "Embedded banking software connecting companies to a network of 20+ partner banks.", categories: ["baas"], tags: ["fiat", "US"] },
  { name: "Synctera", url: "https://synctera.com", docs: "https://docs.synctera.com", description: "BaaS platform pairing fintechs with sponsor banks for accounts, cards, and payments.", categories: ["baas"], tags: ["fiat", "US"] },
  { name: "Column", url: "https://column.com", description: "Developer-focused nationally chartered US bank with direct API access to payment rails.", categories: ["baas", "payments"], tags: ["fiat", "US"] },
  { name: "Increase", url: "https://increase.com", description: "API-first banking with direct connections to ACH, wires, RTP, and cards.", categories: ["baas", "payments"], tags: ["fiat", "US"] },
  { name: "Lead Bank", url: "https://lead.bank", description: "Sponsor bank providing FDIC-insured accounts, BIN sponsorship, and banking APIs.", categories: ["baas", "cards"], tags: ["fiat", "US"] },
  { name: "Cross River", url: "https://crossriver.com", description: "Sponsor bank powering payments, lending, and cards for fintech and crypto companies.", categories: ["baas"], tags: ["fiat", "crypto", "US"] },
  { name: "Grasshopper", url: "https://grasshopper.bank", description: "Digital commercial bank with BaaS programs.", categories: ["baas"], tags: ["fiat", "US"] },
  { name: "Solaris", url: "https://solarisgroup.com", description: "German-licensed embedded finance platform serving European fintechs.", categories: ["baas"], tags: ["fiat", "EU"] },
  { name: "Griffin", url: "https://griffin.com", description: "UK-licensed bank offering API-driven accounts, payments, and safeguarding.", categories: ["baas"], tags: ["fiat", "UK"] },
  { name: "Swan", url: "https://swan.io", description: "European embedded banking: accounts, IBANs, and cards via API.", categories: ["baas"], tags: ["fiat", "EU"] },
  { name: "ClearBank", url: "https://clear.bank", description: "Cloud-native clearing bank providing agency banking and embedded accounts.", categories: ["baas"], tags: ["fiat", "UK", "EU"] },
  { name: "Railsr", url: "https://railsr.com", description: "Embedded finance and cards platform, merged with Equals Money.", categories: ["baas", "cards"], tags: ["fiat", "UK", "EU"] },
  { name: "NymCard", url: "https://nymcard.com", description: "MENA BaaS and issuer processor with Visa USDC settlement.", categories: ["baas", "cards"], tags: ["fiat", "stablecoin", "MENA"] },
  { name: "OpenPayd", url: "https://openpayd.com", description: "Embedded finance platform with IBANs and payment rails.", categories: ["virtual-accounts", "baas"], tags: ["fiat", "EU", "UK"] },
  { name: "Cybrid", url: "https://cybrid.xyz", description: "Embedded crypto and fiat account APIs for US and Canada.", categories: ["ramps", "baas"], tags: ["crypto", "US", "Canada"] },
  { name: "Third National", url: "https://third-national.com", description: "US issuing bank for fintech card programs.", categories: ["cards", "baas"], tags: ["fiat", "US"] },
  { name: "Pomelo", url: "https://pomelo.la", description: "Card issuing and processing across Latin America.", categories: ["cards", "baas"], tags: ["fiat", "LATAM"] },

  // ---- Core banking & ledgers ----
  { name: "Mambu", url: "https://mambu.com", description: "SaaS cloud core banking for deposits, lending, and payments.", categories: ["ledger"], tags: ["fiat", "global"] },
  { name: "Thought Machine", url: "https://thoughtmachine.net", description: "Cloud-native core banking engine with configurable product contracts.", categories: ["ledger"], tags: ["fiat", "global"] },
  { name: "Tuum", url: "https://tuum.com", description: "Modular API-first core banking: accounts, lending, payments, and cards.", categories: ["ledger"], tags: ["fiat", "EU", "UK", "MENA"] },
  { name: "Pismo", url: "https://pismo.io", description: "Visa-owned cloud platform for core banking and issuer processing.", categories: ["ledger", "cards"], tags: ["fiat", "global"] },
  { name: "Temenos", url: "https://temenos.com", description: "Established core banking suite deployed by thousands of banks.", categories: ["ledger"], tags: ["fiat", "global"] },
  { name: "10x Banking", url: "https://10xbanking.com", description: "Cloud-native core banking powering banks like Chase UK and Westpac.", categories: ["ledger"], tags: ["fiat", "UK", "APAC"] },
  { name: "Episode Six", url: "https://episodesix.com", description: "Ledger and card infrastructure for banks and fintechs.", categories: ["ledger", "cards"], tags: ["fiat", "global"] },
  { name: "Formance", url: "https://formance.com", description: "Open-source programmable double-entry ledger and money movement orchestration.", categories: ["ledger"], tags: ["fiat", "crypto", "US", "EU"] },
  { name: "TigerBeetle", url: "https://tigerbeetle.com", description: "Open-source financial transactions database for high-throughput double-entry accounting.", categories: ["ledger"], tags: ["fiat", "global"] },
  { name: "Fragment", url: "https://fragment.dev", description: "GraphQL double-entry ledger API for engineers building money products.", categories: ["ledger"], tags: ["fiat", "US"] },
  { name: "Modern Treasury", url: "https://moderntreasury.com", description: "Payment operations and ledgers unifying bank rails and stablecoins (acquired Beam).", categories: ["payments", "ledger"], tags: ["fiat", "stablecoin", "US"] },

  // ---- Cards & issuing ----
  { name: "Marqeta", url: "https://marqeta.com", description: "Modern card issuing platform powering Cash App, Ramp, and Klarna.", categories: ["cards"], tags: ["fiat", "US", "global"] },
  { name: "Lithic", url: "https://lithic.com", description: "API-first issuer processor for virtual and physical card programs.", categories: ["cards"], tags: ["fiat", "US"] },
  { name: "Highnote", url: "https://highnote.com", description: "Unified issuer processor and program manager for embedded card issuance.", categories: ["cards"], tags: ["fiat", "US"] },
  { name: "Galileo", url: "https://galileo-ft.com", description: "SoFi-owned API platform for card issuing, processing, and program management.", categories: ["cards"], tags: ["fiat", "US", "LATAM"] },
  { name: "i2c", url: "https://i2cinc.com", description: "Credit, debit, and prepaid issuer processing across 200+ countries.", categories: ["cards"], tags: ["fiat", "global"] },
  { name: "Enfuce", url: "https://enfuce.com", description: "Cloud-native issuer processor with EU and UK licenses and BIN sponsorship.", categories: ["cards"], tags: ["fiat", "EU", "UK"] },
  { name: "Thredd", url: "https://thredd.ai", description: "Global issuer processor, formerly GPS, powering fintech card programs.", categories: ["cards"], tags: ["fiat", "EU", "global"] },
  { name: "Adyen", url: "https://adyen.com", description: "Enterprise card issuing unified with acquiring and banking infrastructure.", categories: ["cards", "payments"], tags: ["fiat", "EU", "US", "global"] },
  { name: "Immersve", url: "https://immersve.com", description: "Mastercard principal member issuing cards funded from self-custody wallets.", categories: ["cards"], tags: ["crypto", "APAC", "global"] },
  { name: "Kulipa", url: "https://kulipa.xyz", description: "Stablecoin-native card issuing API for wallets and fintechs.", categories: ["cards"], tags: ["stablecoin", "EU", "global"] },
  { name: "Wirex", url: "https://wirexapp.com", description: "Stablecoin card programs and banking (Wirex Pay).", categories: ["cards"], tags: ["stablecoin", "EU", "UK"] },
  { name: "Monavate", url: "https://monavate.com", description: "UK-regulated card program platform, Mastercard and Visa principal; part of Exodus.", categories: ["cards"], tags: ["fiat", "crypto", "EU", "UK"] },
  { name: "Paymentology", url: "https://paymentology.com", description: "Global issuer processing for banks and fintechs in nearly 70 countries.", categories: ["cards"], tags: ["fiat", "global"] },
  { name: "Visa", url: "https://visa.com", description: "Global card network with stablecoin settlement programs.", categories: ["cards"], tags: ["fiat", "global"] },
  { name: "Signify Holdings", url: "https://signifyholdings.com", description: "Card issuer for stablecoin programs.", categories: ["cards"], tags: ["stablecoin", "US"] },
  { name: "Reap", url: "https://reap.global", description: "Corporate cards and stablecoin payments from Hong Kong.", categories: ["cards", "ramps"], tags: ["stablecoin", "APAC"] },
  { name: "Based App", url: "https://based.one", description: "Visa debit card and account with automatic stablecoin conversion.", categories: ["cards", "ramps", "custody", "swaps"], tags: ["stablecoin", "global"] },

  // ---- KYC & onboarding ----
  { name: "Alloy", url: "https://alloy.com", description: "Identity decisioning platform orchestrating KYC, KYB, and fraud checks.", categories: ["kyc"], tags: ["fiat", "US", "global"] },
  { name: "Sumsub", url: "https://sumsub.com", description: "Full-cycle KYC, KYB, AML screening, and travel rule verification.", categories: ["kyc", "compliance"], tags: ["fiat", "crypto", "global"] },
  { name: "Persona", url: "https://withpersona.com", description: "Configurable identity verification and KYC/KYB orchestration.", categories: ["kyc"], tags: ["fiat", "crypto", "US", "global"] },
  { name: "Entrust (Onfido)", url: "https://entrust.com/products/identity-verification", description: "Document and biometric identity verification, formerly Onfido.", categories: ["kyc"], tags: ["fiat", "crypto", "global"] },
  { name: "Veriff", url: "https://veriff.com", description: "Biometric and document identity verification with fraud detection.", categories: ["kyc"], tags: ["fiat", "crypto", "global"] },
  { name: "Footprint", url: "https://onefootprint.com", description: "KYC, KYB, and onboarding with built-in PII vaulting.", categories: ["kyc"], tags: ["fiat", "US"] },
  { name: "Jumio", url: "https://jumio.com", description: "Identity verification, biometrics, and continuous identity monitoring.", categories: ["kyc"], tags: ["fiat", "crypto", "global"] },
  { name: "Trulioo", url: "https://trulioo.com", description: "Person and business verification covering roughly 195 countries.", categories: ["kyc"], tags: ["fiat", "crypto", "global"] },
  { name: "Incode", url: "https://incode.com", description: "Biometric identity verification with strong Latin America coverage.", categories: ["kyc"], tags: ["fiat", "LATAM", "global"] },
  { name: "Middesk", url: "https://middesk.com", description: "KYB business verification using Secretary of State and licensing records.", categories: ["kyc"], tags: ["fiat", "US"] },

  // ---- Compliance & fraud ----
  { name: "Sardine", url: "https://sardine.ai", description: "Fraud prevention and AML with device and behavior intelligence.", categories: ["compliance"], tags: ["fiat", "crypto", "US", "global"] },
  { name: "Unit21", url: "https://unit21.ai", description: "Transaction monitoring, case management, and financial crime operations.", categories: ["compliance"], tags: ["fiat", "crypto", "global"] },
  { name: "ComplyAdvantage", url: "https://complyadvantage.com", description: "AML risk data, sanctions, PEP, and adverse media screening.", categories: ["compliance"], tags: ["fiat", "global"] },
  { name: "Hummingbird", url: "https://hummingbird.co", description: "Compliance investigation and SAR filing case management.", categories: ["compliance"], tags: ["fiat", "global"] },
  { name: "Chainalysis", url: "https://chainalysis.com", description: "Blockchain analytics for transaction monitoring and investigations.", categories: ["compliance"], tags: ["crypto", "global"] },
  { name: "Elliptic", url: "https://elliptic.co", description: "Crypto AML screening and blockchain analytics.", categories: ["compliance"], tags: ["crypto", "global"] },
  { name: "TRM Labs", url: "https://trmlabs.com", description: "Blockchain intelligence for AML, sanctions, and cross-chain risk.", categories: ["compliance"], tags: ["crypto", "global"] },
  { name: "Feedzai", url: "https://feedzai.com", description: "Enterprise fraud and financial crime prevention for banking.", categories: ["compliance"], tags: ["fiat", "global"] },
  { name: "Lucinity", url: "https://lucinity.com", description: "AML investigation and case management for financial institutions.", categories: ["compliance"], tags: ["fiat", "global"] },
  { name: "Flagright", url: "https://flagright.com", description: "Real-time transaction monitoring across fiat and stablecoin rails.", categories: ["compliance"], tags: ["fiat", "stablecoin", "global"] },
  { name: "Bretton", url: "https://bretton.com", description: "Agents automating KYC, AML, and sanctions operations, formerly Greenlite.", categories: ["compliance"], tags: ["fiat", "US"] },

  // ---- Payment operations ----
  { name: "Moov", url: "https://moov.io", description: "Money movement spanning ACH, RTP, card acquiring, and issuing.", categories: ["payments"], tags: ["fiat", "US"] },
  { name: "Dwolla", url: "https://dwolla.com", description: "Pay-by-bank API unifying ACH, RTP, and FedNow.", categories: ["payments"], tags: ["fiat", "US"] },
  { name: "Astra", url: "https://astrafi.com", description: "Instant disbursements via Visa Direct, Mastercard Move, and ACH.", categories: ["payments"], tags: ["fiat", "US"] },
  { name: "Trice", url: "https://trice.co", description: "Real-time payments gateway over RTP and FedNow.", categories: ["payments"], tags: ["fiat", "US"] },
  { name: "Method", url: "https://methodfi.com", description: "Consumer liability connectivity and payments across 15,000+ institutions.", categories: ["payments", "openbanking"], tags: ["fiat", "US"] },
  { name: "Sila", url: "https://silamoney.com", description: "Money API for ACH, instant settlement, and wallet infrastructure.", categories: ["payments"], tags: ["fiat", "US"] },
  { name: "Deel", url: "https://deel.com", description: "Global payroll with stablecoin pay-ins, payouts, and its DLUSD stablecoin.", categories: ["payments", "ramps"], tags: ["fiat", "stablecoin", "global"] },
  { name: "Rapyd", url: "https://rapyd.net", description: "Global payment collection, disbursement, and wallet infrastructure.", categories: ["payments", "fx", "ramps"], tags: ["fiat", "global"] },
  { name: "Link", url: "https://link.com", description: "Stripe's consumer bank linking and pay-by-bank layer.", categories: ["openbanking", "payments"], tags: ["fiat", "US"] },
  { name: "Flutterwave", url: "https://flutterwave.com", description: "African payment infrastructure with stablecoin integrations.", categories: ["payments", "ramps"], tags: ["fiat", "Africa"] },

  // ---- Cross-border & FX ----
  { name: "Nium", url: "https://nium.com", description: "Real-time cross-border payouts to 190+ countries.", categories: ["fx"], tags: ["fiat", "APAC", "global"] },
  { name: "Thunes", url: "https://thunes.com", description: "Direct global network for payouts across 140 countries.", categories: ["fx"], tags: ["fiat", "global"] },
  { name: "Wise Platform", url: "https://wise.com/platform", description: "Embedded cross-border payments for banks and platforms.", categories: ["fx"], tags: ["fiat", "global"] },
  { name: "Airwallex", url: "https://airwallex.com", description: "Global business accounts, FX conversion, and cross-border payouts.", categories: ["fx", "virtual-accounts"], tags: ["fiat", "APAC", "global"] },
  { name: "Currencycloud", url: "https://currencycloud.com", description: "Multi-currency wallets and FX infrastructure, part of Visa.", categories: ["fx", "virtual-accounts"], tags: ["fiat", "global"] },
  { name: "Ebury", url: "https://ebury.com", description: "Corporate FX, international payments, and lending for SMEs.", categories: ["fx"], tags: ["fiat", "EU", "global"] },
  { name: "Verto", url: "https://verto.co", description: "B2B cross-border payments and FX for Africa and emerging markets.", categories: ["fx"], tags: ["fiat", "Africa", "global"] },
  { name: "Routefusion", url: "https://routefusion.com", description: "Unified API for global FX, SWIFT, and local rails.", categories: ["fx"], tags: ["fiat", "global"] },
  { name: "dLocal", url: "https://dlocal.com", description: "Local payment methods across emerging markets.", categories: ["fx", "ramps"], tags: ["fiat", "LATAM", "Africa", "APAC"] },
  { name: "MoneyGram", url: "https://developer.moneygram.com", description: "Retail cash network with remittance and stablecoin cash in/out APIs.", categories: ["ramps", "fx"], tags: ["fiat", "stablecoin", "global"] },
  { name: "Ripple", url: "https://ripple.com", description: "RLUSD issuer with cross-border rails; acquired Rail and Palisade.", categories: ["stablecoins", "fx"], tags: ["stablecoin", "global"] },
  { name: "OpenFX", url: "https://openfx.com", description: "FX settlement network built on stablecoins.", categories: ["fx", "swaps", "stablecoins"], tags: ["stablecoin", "global"] },

  // ---- Open banking & data ----
  { name: "Plaid", url: "https://plaid.com", description: "Bank connectivity, identity verification, and financial data network.", categories: ["openbanking", "kyc"], tags: ["fiat", "US", "EU"] },
  { name: "MX", url: "https://mx.com", description: "Financial data aggregation and account connectivity.", categories: ["openbanking"], tags: ["fiat", "US"] },
  { name: "Mastercard Open Banking", url: "https://developer.mastercard.com/product/open-banking/", description: "Open banking data and account verification on the Finicity network.", categories: ["openbanking"], tags: ["fiat", "US"] },
  { name: "TrueLayer", url: "https://truelayer.com", description: "European open banking payments and financial data API.", categories: ["openbanking"], tags: ["fiat", "EU", "UK"] },
  { name: "Tink", url: "https://tink.com", description: "Visa-owned European open banking with 6,000+ bank connections.", categories: ["openbanking"], tags: ["fiat", "EU"] },
  { name: "Yapily", url: "https://yapily.com", description: "Open banking infrastructure API across the UK and Europe.", categories: ["openbanking"], tags: ["fiat", "EU", "UK"] },
  { name: "Akoya", url: "https://akoya.com", description: "Consumer-permissioned data network owned by major US institutions.", categories: ["openbanking"], tags: ["fiat", "US"] },
  { name: "Flinks", url: "https://flinks.com", description: "Canadian financial data connectivity and open banking.", categories: ["openbanking"], tags: ["fiat", "Canada"] },
  { name: "Belvo", url: "https://belvo.com", description: "Open finance data and payments for Latin America.", categories: ["openbanking"], tags: ["fiat", "LATAM"] },
  { name: "Mono", url: "https://mono.co", description: "African open banking APIs for data, payments, and identity.", categories: ["openbanking"], tags: ["fiat", "Africa"] },
  { name: "Mesh", url: "https://meshconnect.com", description: "Account aggregation, crypto deposits, and transfers.", categories: ["ramps", "swaps", "openbanking"], tags: ["crypto", "US", "global"] },

  // ---- Virtual accounts ----
  { name: "Brale", url: "https://brale.xyz", docs: "https://docs.brale.xyz", description: "Stablecoin issuance platform with virtual accounts and ramps.", categories: ["stablecoins", "virtual-accounts", "ramps"], tags: ["stablecoin", "US"] },
  { name: "Iron", url: "https://iron.xyz", description: "US and EU deposit accounts for bank-to-wallet flows.", categories: ["virtual-accounts", "ramps"], tags: ["stablecoin", "US", "EU"] },
  { name: "Conduit", url: "https://conduitpay.com", description: "Multicurrency virtual accounts and stablecoin cross-border payments.", categories: ["virtual-accounts", "ramps", "fx"], tags: ["stablecoin", "Africa", "LATAM", "global"] },
  { name: "Due", url: "https://opendue.com", description: "European payment rails with stablecoin settlement.", categories: ["virtual-accounts", "ramps"], tags: ["stablecoin", "EU"] },
  { name: "Depa", url: "https://depa.finance", description: "Payment orchestration and global virtual deposit accounts.", categories: ["virtual-accounts", "ramps"], tags: ["stablecoin", "global"] },
  { name: "Mesta", url: "https://mesta.xyz", description: "Stablecoin and fiat cross-border payment network.", categories: ["virtual-accounts", "ramps", "fx"], tags: ["stablecoin", "global"] },
  { name: "Damex", url: "https://damex.io", description: "Digital asset payment accounts for businesses.", categories: ["virtual-accounts", "ramps"], tags: ["crypto", "EU"] },
  { name: "Tazapay", url: "https://tazapay.com", description: "Cross-border payments and collections across Asia-Pacific.", categories: ["virtual-accounts", "ramps", "fx"], tags: ["fiat", "APAC"] },
  { name: "PhotonPay", url: "https://photonpay.com", description: "Global accounts and card issuing from Hong Kong.", categories: ["virtual-accounts", "cards"], tags: ["fiat", "APAC"] },
  { name: "KOSH", url: "https://koshmoney.com", description: "Stablecoin accounts, payments, and cards.", categories: ["virtual-accounts", "ramps", "cards"], tags: ["stablecoin", "global"] },
  { name: "Noah", url: "https://noah.com", description: "Global accounts and stablecoin payment rails.", categories: ["virtual-accounts", "ramps"], tags: ["stablecoin", "global"] },
  { name: "Monerium", url: "https://monerium.com", description: "Regulated EURe and GBPe e-money with personal IBANs.", categories: ["stablecoins", "virtual-accounts"], tags: ["stablecoin", "EU"] },
  { name: "Noxxo", url: "https://noxxo.com", description: "Virtual account infrastructure.", categories: ["virtual-accounts"], tags: ["fiat"] },

  // ---- Onramps & offramps ----
  { name: "MoonPay", url: "https://moonpay.com", description: "Consumer on and off ramp widget, swaps, and balances.", categories: ["ramps", "swaps"], tags: ["crypto", "global"] },
  { name: "Transak", url: "https://transak.com", description: "Global fiat-crypto on and off ramp widget and APIs.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Ramp Network", url: "https://rampnetwork.com", description: "Regulated onramp and offramp widget covering 150+ countries.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Meld", url: "https://meld.io", description: "Ramp aggregator routing across 50+ providers in 184 countries.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Onramper", url: "https://onramper.com", description: "Fiat-to-crypto aggregator with 30+ onramps and 175+ payment methods.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "AlchemyPay", url: "https://alchemypay.org", description: "Fiat-crypto payment gateway with local payment methods.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "BTC Direct", url: "https://btcdirect.eu", description: "European crypto on-ramp.", categories: ["ramps"], tags: ["crypto", "EU"] },
  { name: "Banxa", url: "https://banxa.com", description: "Fiat on and off ramps with local payment methods.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Binance Connect", url: "https://binance.com", description: "On-ramp and crypto liquidity from Binance.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Blockchain.com", url: "https://blockchain.com", description: "Wallet and exchange with on-ramp APIs.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "BoomFi", url: "https://boomfi.xyz", description: "Crypto payments and light-KYC ramps.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Coinbase Developer Platform", url: "https://coinbase.com/developer-platform", description: "Embedded wallets, onramps, and exchange rails from Coinbase.", categories: ["ramps", "custody"], tags: ["crypto", "US", "global"] },
  { name: "Eldorado", url: "https://eldorado.io", description: "P2P-powered ramps across Latin America.", categories: ["ramps"], tags: ["crypto", "LATAM"] },
  { name: "Fonbnk", url: "https://fonbnk.com", description: "Airtime and mobile money to stablecoin ramps across Africa.", categories: ["ramps"], tags: ["stablecoin", "Africa"] },
  { name: "Guardarian", url: "https://guardarian.com", description: "No-registration fiat-crypto exchange for EU.", categories: ["ramps"], tags: ["crypto", "EU"] },
  { name: "Koywe", url: "https://koywe.com", description: "Ramps for Chile, Mexico, Argentina, and Colombia.", categories: ["ramps"], tags: ["crypto", "LATAM"] },
  { name: "Kryptonim", url: "https://kryptonim.com", description: "EU and UK crypto purchase flows.", categories: ["ramps"], tags: ["crypto", "EU", "UK"] },
  { name: "Onmeta", url: "https://onmeta.in", description: "INR on and off ramps for India.", categories: ["ramps"], tags: ["crypto", "APAC"] },
  { name: "Onramp Money", url: "https://onramp.money", description: "India-focused fiat-crypto funding.", categories: ["ramps"], tags: ["crypto", "APAC"] },
  { name: "PayPal", url: "https://paypal.com", description: "PYUSD issuer with consumer crypto and checkout rails.", categories: ["ramps", "stablecoins"], tags: ["fiat", "stablecoin", "US", "global"] },
  { name: "Paybis", url: "https://paybis.com", description: "White-label onramp and offramp API in 180+ countries.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Revolut Ramp", url: "https://revolut.com", description: "Crypto ramp from Revolut for EU and UK users.", categories: ["ramps"], tags: ["crypto", "EU", "UK"] },
  { name: "Robinhood Connect", url: "https://robinhood.com", description: "US retail on-ramp into external wallets.", categories: ["ramps"], tags: ["crypto", "US"] },
  { name: "Shift4", url: "https://shift4.com", description: "Card acquiring with crypto payout integrations.", categories: ["ramps"], tags: ["fiat", "global"] },
  { name: "Simplex", url: "https://simplex.com", description: "Card-based crypto on-ramp, part of Nuvei.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Skrill", url: "https://skrill.com", description: "Digital wallet with crypto buy and sell.", categories: ["ramps"], tags: ["crypto", "EU", "UK"] },
  { name: "Swapped", url: "https://swapped.com", description: "European crypto purchase ramps.", categories: ["ramps"], tags: ["crypto", "EU"] },
  { name: "Topper", url: "https://topperpay.com", description: "Card-based on-ramp by Uphold.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "TransFi", url: "https://transfi.com", description: "Ramps and payouts across emerging markets.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Unlimit", url: "https://unlimit.com", description: "Global acquiring with crypto ramp services.", categories: ["ramps"], tags: ["crypto", "global"] },
  { name: "Yellow Card", url: "https://yellowcard.io", description: "Stablecoin ramps across 20+ African markets.", categories: ["ramps"], tags: ["stablecoin", "Africa"] },
  { name: "Sphere", url: "https://spherepay.co", description: "Stablecoin payment and cross-border APIs.", categories: ["ramps", "stablecoins", "fx"], tags: ["stablecoin", "global"] },
  { name: "HopNow", url: "https://hopnow.io", description: "Cross-chain payment routing and ramps.", categories: ["ramps", "swaps"], tags: ["stablecoin", "global"] },
  { name: "Merge Money", url: "https://merge.money", description: "Stablecoin banking and settlement APIs.", categories: ["ramps", "stablecoins"], tags: ["stablecoin", "global"] },
  { name: "Fipto", url: "https://fipto.com", description: "Stablecoin treasury and payment APIs from France.", categories: ["ramps", "stablecoins"], tags: ["stablecoin", "EU"] },
  { name: "Bitso", url: "https://bitso.com", description: "Bitso Business ramps across Mexico, Brazil, Argentina, and Colombia.", categories: ["ramps"], tags: ["crypto", "LATAM"] },
  { name: "BlindPay", url: "https://blindpay.com", description: "Stablecoin ramps for Brazil.", categories: ["ramps"], tags: ["stablecoin", "LATAM"] },
  { name: "Avenia", url: "https://avenia.io", description: "Brazilian real stablecoin rails and ramps.", categories: ["ramps", "stablecoins"], tags: ["stablecoin", "LATAM"] },
  { name: "Fasset", url: "https://fasset.com", description: "Digital asset platform for UAE, Indonesia, Malaysia, and India.", categories: ["ramps"], tags: ["crypto", "MENA", "APAC"] },
  { name: "Hubpay", url: "https://hubpay.io", description: "UAE remittance and crypto ramp.", categories: ["ramps"], tags: ["crypto", "MENA"] },
  { name: "Fuze", url: "https://fuze.finance", description: "Digital asset infrastructure for MENA banks and fintechs.", categories: ["ramps", "custody"], tags: ["crypto", "MENA"] },
  { name: "Juicyway", url: "https://juicyway.com", description: "Stablecoin-powered payments for Africa.", categories: ["ramps"], tags: ["stablecoin", "Africa"] },
  { name: "NALA Rafiki", url: "https://rafiki.com", description: "Payment rails into East Africa from NALA.", categories: ["ramps", "fx"], tags: ["fiat", "Africa"] },
  { name: "Ivorypay", url: "https://ivorypay.io", description: "Stablecoin payments for Nigeria, Ghana, Kenya, and South Africa.", categories: ["ramps"], tags: ["stablecoin", "Africa"] },
  { name: "Quidax", url: "https://quidax.com", description: "Nigerian exchange with ramp APIs.", categories: ["ramps"], tags: ["crypto", "Africa"] },
  { name: "Paychant", url: "https://paychant.com", description: "African on and off ramp APIs.", categories: ["ramps"], tags: ["crypto", "Africa"] },
  { name: "VALR", url: "https://valr.com", description: "South African exchange with payment rails.", categories: ["ramps"], tags: ["crypto", "Africa"] },
  { name: "Kotani Pay", url: "https://kotanipay.com", description: "Stablecoin to mobile money APIs across Africa.", categories: ["ramps"], tags: ["stablecoin", "Africa"] },
  { name: "FOMO Pay", url: "https://fomopay.com", description: "Singapore payment institution with digital asset rails.", categories: ["ramps"], tags: ["fiat", "APAC"] },
  { name: "StraitsX", url: "https://straitsx.com", description: "XSGD issuer and payment infrastructure for Singapore and Indonesia.", categories: ["ramps", "stablecoins"], tags: ["stablecoin", "APAC"] },
  { name: "Coins.ph", url: "https://coins.ph", description: "Philippines crypto platform with ramp APIs.", categories: ["ramps"], tags: ["crypto", "APAC"] },

  // ---- Custody & wallets ----
  { name: "Privy", url: "https://privy.io", description: "Embedded wallets and onboarding, part of Stripe.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Turnkey", url: "https://turnkey.com", description: "Key management and wallet infrastructure API.", categories: ["custody"], tags: ["crypto", "US", "global"] },
  { name: "Dfns", url: "https://dfns.co", description: "MPC wallets-as-a-service securing 10M+ wallets.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Web3Auth", url: "https://web3auth.io", description: "Embedded wallet SDK with social login, part of Consensys.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Portal", url: "https://portalhq.io", description: "MPC embedded wallets and APIs for stablecoin payments.", categories: ["custody"], tags: ["stablecoin", "global"] },
  { name: "Utila", url: "https://utila.io", description: "Institutional MPC wallets focused on stablecoin operations.", categories: ["custody"], tags: ["stablecoin", "global"] },
  { name: "Cobo", url: "https://cobo.com", description: "MPC custody and wallet-as-a-service across 80+ chains.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Copper", url: "https://copper.co", description: "Institutional custody, off-exchange settlement, and prime services.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Anchorage Digital", url: "https://anchorage.com", description: "Federally chartered crypto bank: custody, staking, and stablecoin issuance.", categories: ["custody", "stablecoins"], tags: ["crypto", "US"] },
  { name: "Fireblocks", url: "https://fireblocks.com", description: "Institutional custody, wallets, and tokenization platform.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "BitGo", url: "https://bitgo.com", description: "Qualified custodian with wallet and settlement APIs.", categories: ["custody"], tags: ["crypto", "US", "global"] },
  { name: "Bastion", url: "https://bastion.com", description: "NYDFS-chartered wallet and stablecoin issuance infrastructure.", categories: ["custody", "stablecoins", "ramps"], tags: ["stablecoin", "US"] },
  { name: "Para", url: "https://getpara.com", description: "Embedded wallets that work across apps and chains.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Dynamic", url: "https://dynamic.xyz", description: "Wallet auth and embedded wallet infrastructure.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "thirdweb", url: "https://thirdweb.com", description: "Web3 development platform with smart wallets.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Magic", url: "https://magic.link", description: "Email-login embedded wallets.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "ZeroDev", url: "https://zerodev.app", description: "Smart wallets with account abstraction and social login.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Safe", url: "https://safe.global", description: "Smart account standard and multisig infrastructure.", categories: ["custody"], tags: ["crypto", "global"] },
  { name: "Seismic", url: "https://seismic.systems", description: "Encrypted blockchain infrastructure.", categories: ["custody"], tags: ["crypto"] },
  { name: "Umbra", url: "https://umbra.cash", description: "Privacy-preserving payments and custody.", categories: ["custody"], tags: ["crypto"] },
  { name: "Tria", url: "https://tria.so", description: "Chain-abstracted accounts and intent routing (BestPath AVS).", categories: ["custody", "swaps"], tags: ["crypto", "global"] },
  { name: "Phantom", url: "https://phantom.com", description: "Self-custodial wallet with Phantom Cash and CASH stablecoin.", categories: ["custody"], tags: ["crypto", "US", "global"] },
  { name: "Payy", url: "https://payy.network", description: "Non-custodial stablecoin wallet on an Ethereum-secured ZK L2.", categories: ["custody", "networks"], tags: ["stablecoin", "global"] },

  // ---- Stablecoins ----
  { name: "Circle", url: "https://circle.com", description: "USDC and EURC issuer with programmable wallets, contracts, and CCTP.", categories: ["stablecoins", "custody", "ramps"], tags: ["stablecoin", "US", "global"] },
  { name: "Tether", url: "https://tether.to", description: "Issuer of USDT, the largest stablecoin by supply.", categories: ["stablecoins"], tags: ["stablecoin", "global"] },
  { name: "Paxos", url: "https://paxos.com", description: "NYDFS-regulated white-label stablecoin issuer behind PYUSD and USDG.", categories: ["stablecoins"], tags: ["stablecoin", "US"] },
  { name: "M0", url: "https://m0.org", description: "Onchain protocol for minting branded stablecoins on shared collateral.", categories: ["stablecoins"], tags: ["stablecoin", "global"] },
  { name: "Agora", url: "https://agora.finance", description: "White-label stablecoins built on AUSD with institutional reserves.", categories: ["stablecoins"], tags: ["stablecoin", "global"] },
  { name: "Stably", url: "https://stably.io", description: "Stablecoin-as-a-service supporting 20+ branded launches.", categories: ["stablecoins"], tags: ["stablecoin", "global"] },
  { name: "Ethena", url: "https://ethena.fi", description: "Synthetic dollar USDe with native yield.", categories: ["stablecoins", "yield"], tags: ["stablecoin", "global"] },
  { name: "BiLira", url: "https://bilira.co", description: "Turkish lira stablecoin (TRYB) and local ramps.", categories: ["stablecoins", "ramps"], tags: ["stablecoin", "MENA"] },
  { name: "ether.fi", url: "https://ether.fi", description: "Staking and neobank stack with LiquidUSD yield.", categories: ["yield", "stablecoins"], tags: ["crypto", "global"] },

  // ---- Settlement networks ----
  { name: "Ethereum", url: "https://ethereum.org", description: "The largest EVM settlement layer.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Base", url: "https://base.org", description: "Coinbase's Ethereum L2.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Solana", url: "https://solana.com", description: "High-throughput network with SPL token rails.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Polygon", url: "https://polygon.technology", description: "Low-fee EVM network for payments and real-world assets.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Stellar", url: "https://stellar.org", description: "Payment-focused network with anchor cash-out rails.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Tron", url: "https://tron.network", description: "Network carrying a large share of USDT transfers.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Arbitrum", url: "https://arbitrum.io", description: "Ethereum L2 rollup.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Optimism", url: "https://optimism.io", description: "Ethereum L2 and the OP Stack.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Gnosis Chain", url: "https://gnosis.io", description: "EVM network behind Gnosis Pay cards.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Plasma", url: "https://plasma.to", description: "Stablecoin-optimized blockchain.", categories: ["networks"], tags: ["stablecoin", "global"] },
  { name: "Tempo", url: "https://tempo.xyz", description: "Payments-focused chain incubated by Stripe and Paradigm.", categories: ["networks"], tags: ["stablecoin", "global"] },
  { name: "Scroll", url: "https://scroll.io", description: "Ethereum zk-rollup L2.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Sui", url: "https://sui.io", description: "Move-based high-throughput network.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "TON", url: "https://ton.org", description: "Network integrated with Telegram distribution.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "XRP Ledger", url: "https://xrpl.org", description: "Payment-focused ledger with native DEX.", categories: ["networks"], tags: ["crypto", "global"] },
  { name: "Codex", url: "https://codex.xyz", description: "Stablecoin-focused Ethereum L2.", categories: ["networks", "swaps"], tags: ["stablecoin", "global"] },

  // ---- Swaps & bridging ----
  { name: "LI.FI", url: "https://li.fi", description: "Bridge and swap aggregation API.", categories: ["swaps"], tags: ["crypto", "global"] },
  { name: "Socket", url: "https://socket.tech", description: "Unified cross-chain routing protocol.", categories: ["swaps"], tags: ["crypto", "global"] },
  { name: "0x", url: "https://0x.org", description: "DEX aggregation and swap APIs.", categories: ["swaps"], tags: ["crypto", "global"] },
  { name: "Squid", url: "https://squidrouter.com", description: "Cross-chain swap router built on Axelar.", categories: ["swaps"], tags: ["crypto", "global"] },
  { name: "Across", url: "https://across.to", description: "Intent-based bridging protocol.", categories: ["swaps"], tags: ["crypto", "global"] },
  { name: "Wormhole", url: "https://wormhole.com", description: "Cross-chain messaging and bridging.", categories: ["swaps"], tags: ["crypto", "global"] },
  { name: "Relay", url: "https://relay.link", description: "Instant cross-chain swaps and payments.", categories: ["swaps"], tags: ["crypto", "global"] },
  { name: "Router Protocol", url: "https://routerprotocol.com", description: "Cross-chain routing infrastructure.", categories: ["swaps"], tags: ["crypto", "global"] },

  // ---- Yield & earn ----
  { name: "Yield.xyz", url: "https://yield.xyz", description: "Yield infrastructure API across chains.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Blend", url: "https://blend.money", description: "Stablecoin yield aggregation.", categories: ["yield"], tags: ["stablecoin", "global"] },
  { name: "Veda", url: "https://veda.tech", description: "Vault infrastructure powering earn products.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Ondo Finance", url: "https://ondo.finance", description: "Tokenized treasuries and institutional yield.", categories: ["yield", "stablecoins"], tags: ["stablecoin", "US", "global"] },
  { name: "Jupiter Lend", url: "https://jup.ag", description: "Lending on Solana from Jupiter.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Fluid", url: "https://fluid.io", description: "Lending and DEX liquidity layer.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Morpho", url: "https://morpho.org", description: "Open lending infrastructure used by earn products.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Sentora", url: "https://sentora.com", description: "DeFi risk analytics and vault curation.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Gauntlet", url: "https://gauntlet.xyz", description: "Risk management and vault curation.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Aave", url: "https://aave.com", description: "The largest onchain lending protocol.", categories: ["yield"], tags: ["crypto", "global"] },
  { name: "Upshift", url: "https://upshift.finance", description: "Institutional-grade yield vaults.", categories: ["yield"], tags: ["crypto", "global"] },
];
